title: "EKANGA MBIDA Saint Wilfried"
logo: img/nny.jpg
description: "Portfolio Etudiant en Microbiologie medicale et Biostatistique, Data Analyst"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
